### ISSUE TITLE
Wrong highlight if variable name contains "_From"

### ISSUE THREAD

**Issue by Dragon1308** [dalbitresb12/vscode-language-bqsql#1]
### Description
Wrong highlight if variable name contains "_From":

![image](https://github.com/user-attachments/assets/bdcde13d-b715-4d89-a852-d0df4a67bb09)

**Comment by dalbitresb12** [comment]
Hello, I'm most definitely not an expert in TM grammars, but I think the change I just made should fix the issue.

I've just published v2.0.1 which includes the fix for this.

Thanks for reporting, let me know if you find anything else.

**Comment by Dragon1308** [comment]
Hi! Thank you, it works!
